"""Merge the confirmed cases generated by ny_data_scraper.py into
COVID-19/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv
"""
import csv
import os
import logging

import pandas

COUNTIES = [
    'Albany', 'Allegany', 'Bronx', 'Broome', 'Cattaraugus', 'Cayuga',
    'Chautauqua', 'Chemung', 'Chenango', 'Clinton', 'Columbia', 'Cortland',
    'Delaware', 'Dutchess', 'Erie', 'Essex', 'Franklin', 'Fulton', 'Genesee',
    'Greene', 'Hamilton', 'Herkimer', 'Jefferson', 'Kings', 'Lewis',
    'Livingston', 'Madison', 'Monroe', 'Montgomery', 'Nassau', 'New York',
    'Niagara', 'Oneida', 'Onondaga', 'Ontario', 'Orange', 'Orleans', 'Oswego',
    'Otsego', 'Putnam', 'Queens', 'Rensselaer', 'Richmond', 'Rockland',
    'St. Lawrence', 'Saratoga', 'Schenectady', 'Schoharie', 'Schuyler',
    'Seneca', 'Steuben', 'Suffolk', 'Sullivan', 'Tioga', 'Tompkins', 'Ulster',
    'Warren', 'Washington', 'Wayne', 'Westchester', 'Wyoming', 'Yates'
]

LOGGER = logging.getLogger('merge_in_confirmed_cases')

CSV_FILE_NAME = os.path.join(
    os.path.dirname(__file__), 'ny_confirmed_cases.csv'
)


def setup_logger():
    """Set up the logger"""
    logging.basicConfig(
        level=logging.NOTSET, format='%(asctime) %(message)s'
    )


def merge_in_confirmed_cases():
    """Merge in confirmed cases"""
    data = pandas.read_csv(CSV_FILE_NAME, parse_dates=[2]).sort_values(
        ['Location', 'Timestamp']
    )
    data['Timestamp'] = data['Timestamp'].dt.date
    print(data)
    # print(data)


def main():
    """Set up the logger and merge in the file"""
    setup_logger()
    merge_in_confirmed_cases()


if __name__ == '__main__':
    main()
